name: Build main target

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    branches:
      - master
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-14
    if: github.event.pull_request.draft == false
    env:
      PROJECT: Nextcloud.xcodeproj
      DESTINATION: platform=iOS Simulator,name=iPhone 14
      SCHEME: Nextcloud
      SERVER_BRANCH: stable28
    steps:
    - name: Set env var
      run: echo "DEVELOPER_DIR=$(xcode-select --print-path)" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: Setup Bundler and Install Gems
      run: |
        gem install bundler
        bundle install
        bundle update
    - name: Restore Carhage Cache
      uses: actions/cache@v3
      id: carthage-cache
      with:
        path: Carthage
        key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
        restore-keys: |
          ${{ runner.os }}-carthage-
    - name: Carthage
      if: steps.carthage-cache.outputs.cache-hit != 'true'
      run: carthage bootstrap --use-xcframeworks --platform iOS
    - name: Download GoogleService-Info.plist
      run: wget "https://raw.githubusercontent.com/firebase/quickstart-ios/master/mock-GoogleService-Info.plist" -O GoogleService-Info.plist
    - name: Checkout server
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        submodules: true
        repository: nextcloud/server
        path: server
        ref: $SERVER_BRANCH
    - name: Set up Nextcloud
      run: |
        mkdir server/data
        ./server/occ maintenance:install --verbose --database=sqlite --database-name=nextcloud --database-host=127.0.0.1 --database-user=root --database-pass=rootpassword --admin-user admin --admin-pass admin
        ./server/occ config:system:set hashing_default_password --value=true --type=boolean
        ./server/occ config:system:set memcache.local --value="\\OC\\Memcache\\APCu"
        ./server/occ config:system:set memcache.distributed --value="\\OC\\Memcache\\APCu"
        PHP_CLI_SERVER_WORKERS=3 php -S localhost:8080 -t server/ &
    - name: Create docker test server and export enviroment variables
      run: |
        source ./create-docker-test-server.sh
    - name: Build & Test Nextcloud iOS
      run: |
        set -o pipefail && xcodebuild clean test -project $PROJECT \
        -scheme "$SCHEME" \
        -destination "$DESTINATION" \
        -enableCodeCoverage YES \
        -test-iterations 3 \
        -retry-tests-on-failure \
        | xcpretty
    - name: Upload coverage to codecov
      run: |
        bundle exec slather
        bash <(curl -s https://codecov.io/bash) -f ./cobertura.xml -X coveragepy -X gcov -X xcode -t ${{ secrets.CODECOV_TOKEN }}

